import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const myFont = localFont({ src: "./Roboto-Regular.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <main className="flex min-h-screen flex-col items-center justify-center bg-slate-400">
          {children}
        </main>
      </body>
    </html>
  );
}
